(function (root) {
  "use strict";

  /**
   * Learner-oriented MSA lexicon: Latin phonetic keys → Arabic + vocalized form.
   * Used for Yamli-like suggestions and the local tashkīl fallback.
   */
  var ENTRIES = [
    { k: ["marhaba", "marhabaa", "merhaba", "marhaban"], ar: "مرحبا", t: "مَرْحَبًا" },
    { k: ["ahlan", "ahlanwasahlan", "ahlanwa sahlan"], ar: "أهلا", t: "أَهْلًا" },
    { k: ["salam", "salaam", "salamun"], ar: "سلام", t: "سَلَامٌ" },
    { k: ["alsalam", "asselam", "assalam"], ar: "السلام", t: "السَّلَامُ" },
    { k: ["alsalamualaykum", "assalamualaykum", "salamualaykum", "salamoualaykoum", "salamu alaykum"], ar: "السلام عليكم", t: "السَّلَامُ عَلَيْكُمْ" },
    { k: ["waalaykumsalam", "walaykumsalam", "waalaykoum", "waalaykum"], ar: "وعليكم السلام", t: "وَعَلَيْكُمُ السَّلَامُ" },
    { k: ["sabah", "sabaah"], ar: "صباح", t: "صَبَاحُ" },
    { k: ["sabahalkhayr", "sabah el khayr", "sabahalkheir"], ar: "صباح الخير", t: "صَبَاحُ الْخَيْرِ" },
    { k: ["masa", "masaa"], ar: "مساء", t: "مَسَاءُ" },
    { k: ["masaalkhayr", "masaelkhayr"], ar: "مساء الخير", t: "مَسَاءُ الْخَيْرِ" },
    { k: ["shukran", "choukran", "shokran", "chokran"], ar: "شكرا", t: "شُكْرًا" },
    { k: ["afwan", "3afwan"], ar: "عفوا", t: "عَفْوًا" },
    { k: ["minfadlik", "minfadlek", "minfadlak"], ar: "من فضلك", t: "مِنْ فَضْلِكَ" },
    { k: ["minfadiliki", "minfadlikki"], ar: "من فضلك", t: "مِنْ فَضْلِكِ" },
    { k: ["naam", "na3am", "naem", "nam"], ar: "نعم", t: "نَعَمْ" },
    { k: ["la", "laa"], ar: "لا", t: "لَا" },
    { k: ["inshallah", "inchaallah", "inchallah", "enshallah"], ar: "إن شاء الله", t: "إِنْ شَاءَ اللَّهُ" },
    { k: ["mashallah", "machallah", "mashaallah"], ar: "ما شاء الله", t: "مَا شَاءَ اللَّهُ" },
    { k: ["alhamdulillah", "alhamdoulilah", "hamdulillah"], ar: "الحمد لله", t: "الْحَمْدُ لِلَّهِ" },
    { k: ["bismillah", "bismillahirrahman"], ar: "بسم الله", t: "بِسْمِ اللَّهِ" },
    { k: ["kayfa", "kayf", "keif", "kif", "kaifa"], ar: "كيف", t: "كَيْفَ" },
    { k: ["kayfahaluk", "kayfahalouk", "kifhalak", "keifhalak"], ar: "كيف حالك", t: "كَيْفَ حَالُكَ" },
    { k: ["haluk", "halak", "halek", "halouk"], ar: "حالك", t: "حَالُكَ" },
    { k: ["haluki", "halik"], ar: "حالك", t: "حَالُكِ" },
    { k: ["ma", "maa", "madha", "mada"], ar: "ما", t: "مَا" },
    { k: ["madha", "matha"], ar: "ماذا", t: "مَاذَا" },
    { k: ["man"], ar: "من", t: "مَنْ" },
    { k: ["ayna", "aynaa"], ar: "أين", t: "أَيْنَ" },
    { k: ["mata", "mataa"], ar: "متى", t: "مَتَى" },
    { k: ["limadha", "limatha", "lech", "lechou"], ar: "لماذا", t: "لِمَاذَا" },
    { k: ["kam"], ar: "كم", t: "كَمْ" },
    { k: ["hal"], ar: "هل", t: "هَلْ" },
    { k: ["ana", "anaa"], ar: "أنا", t: "أَنَا" },
    { k: ["anta", "ente", "inta"], ar: "أنت", t: "أَنْتَ" },
    { k: ["anti", "enti"], ar: "أنت", t: "أَنْتِ" },
    { k: ["huwa", "howa", "houwa"], ar: "هو", t: "هُوَ" },
    { k: ["hiya", "hiyaa", "hia"], ar: "هي", t: "هِيَ" },
    { k: ["nahnu", "nahna", "nahnou"], ar: "نحن", t: "نَحْنُ" },
    { k: ["antum", "entom"], ar: "أنتم", t: "أَنْتُمْ" },
    { k: ["antunna", "entonna"], ar: "أنتن", t: "أَنْتُنَّ" },
    { k: ["hum", "houm"], ar: "هم", t: "هُمْ" },
    { k: ["hunna", "hounna"], ar: "هن", t: "هُنَّ" },
    { k: ["anta", "int"], ar: "أنت", t: "أَنْتَ" },
    { k: ["hatha", "hadha", "hada"], ar: "هذا", t: "هَذَا" },
    { k: ["hathihi", "hadhihi", "hadihi"], ar: "هذه", t: "هَذِهِ" },
    { k: ["dhalika", "thalika", "zalek"], ar: "ذلك", t: "ذَلِكَ" },
    { k: ["tilka"], ar: "تلك", t: "تِلْكَ" },
    { k: ["alladhi", "allazi", "elli"], ar: "الذي", t: "الَّذِي" },
    { k: ["allati", "ellati"], ar: "التي", t: "الَّتِي" },
    { k: ["fi", "fee", "fii"], ar: "في", t: "فِي" },
    { k: ["min"], ar: "من", t: "مِنْ" },
    { k: ["ila", "ila", "ila"], ar: "إلى", t: "إِلَى" },
    { k: ["ala", "3ala", "alaa"], ar: "على", t: "عَلَى" },
    { k: ["an", "3an"], ar: "عن", t: "عَنْ" },
    { k: ["ma3a", "maa3", "ma3"], ar: "مع", t: "مَعَ" },
    { k: ["qabla", "kabl", "qabl"], ar: "قبل", t: "قَبْلَ" },
    { k: ["ba3da", "baada", "ba3d"], ar: "بعد", t: "بَعْدَ" },
    { k: ["tahta"], ar: "تحت", t: "تَحْتَ" },
    { k: ["fawqa", "fawk"], ar: "فوق", t: "فَوْقَ" },
    { k: ["bayna", "bin"], ar: "بين", t: "بَيْنَ" },
    { k: ["inda", "3inda", "3and"], ar: "عند", t: "عِنْدَ" },
    { k: ["lakin", "lakinna", "laken"], ar: "لكن", t: "لَكِنْ" },
    { k: ["wa", "w"], ar: "و", t: "وَ" },
    { k: ["aw", "aw"], ar: "أو", t: "أَوْ" },
    { k: ["thumma", "thoma", "soumma"], ar: "ثم", t: "ثُمَّ" },
    { k: ["idha", "itha", "iza"], ar: "إذا", t: "إِذَا" },
    { k: ["in"], ar: "إن", t: "إِنْ" },
    { k: ["anna"], ar: "أن", t: "أَنَّ" },
    { k: ["li"], ar: "ل", t: "لِ" },
    { k: ["bi"], ar: "ب", t: "بِ" },
    { k: ["ka"], ar: "ك", t: "كَ" },
    { k: ["qad"], ar: "قد", t: "قَدْ" },
    { k: ["sawfa", "saufa"], ar: "سوف", t: "سَوْفَ" },
    { k: ["lan"], ar: "لن", t: "لَنْ" },
    { k: ["lam"], ar: "لم", t: "لَمْ" },
    { k: ["laysa", "laysat"], ar: "ليس", t: "لَيْسَ" },
    { k: ["kana", "kana"], ar: "كان", t: "كَانَ" },
    { k: ["yakunu", "yakoun"], ar: "يكون", t: "يَكُونُ" },
    { k: ["yuridu", "yurid", "yebghi"], ar: "يريد", t: "يُرِيدُ" },
    { k: ["uridu", "urid", "ourid"], ar: "أريد", t: "أُرِيدُ" },
    { k: ["uhibbu", "uhib", "ouheb", "ahib"], ar: "أحب", t: "أُحِبُّ" },
    { k: ["aktubu", "aktub", "ekteb"], ar: "أكتب", t: "أَكْتُبُ" },
    { k: ["aqrahu", "aqra", "eqra"], ar: "أقرأ", t: "أَقْرَأُ" },
    { k: ["afhamu", "afham", "efham"], ar: "أفهم", t: "أَفْهَمُ" },
    { k: ["ata3allamu", "atallam", "at3allam"], ar: "أتعلم", t: "أَتَعَلَّمُ" },
    { k: ["adrusu", "adrus", "edrus"], ar: "أدرس", t: "أَدْرُسُ" },
    { k: ["adhhabu", "adhhab", "arouh"], ar: "أذهب", t: "أَذْهَبُ" },
    { k: ["akulu", "akul", "akel"], ar: "آكل", t: "آكُلُ" },
    { k: ["ashrabu", "ashrab", "echrab"], ar: "أشرب", t: "أَشْرَبُ" },
    { k: ["qala", "qal"], ar: "قال", t: "قَالَ" },
    { k: ["yaqulu", "yaqul", "yeqoul"], ar: "يقول", t: "يَقُولُ" },
    { k: ["fa3ala", "faala"], ar: "فعل", t: "فَعَلَ" },
    { k: ["kataba"], ar: "كتب", t: "كَتَبَ" },
    { k: ["qaraa", "qara"], ar: "قرأ", t: "قَرَأَ" },
    { k: ["fahima", "fahm"], ar: "فهم", t: "فَهِمَ" },
    { k: ["ta3allama", "taallama"], ar: "تعلم", t: "تَعَلَّمَ" },
    { k: ["darasa"], ar: "درس", t: "دَرَسَ" },
    { k: ["dhahaba", "dahaba"], ar: "ذهب", t: "ذَهَبَ" },
    { k: ["jae", "jaa", "ja2a"], ar: "جاء", t: "جَاءَ" },
    { k: ["raa", "ra2a"], ar: "رأى", t: "رَأَى" },
    { k: ["samia", "sami3a"], ar: "سمع", t: "سَمِعَ" },
    { k: ["3arafa", "arafa"], ar: "عرف", t: "عَرَفَ" },
    { k: ["3amila", "amila"], ar: "عمل", t: "عَمِلَ" },
    { k: ["sakana"], ar: "سكن", t: "سَكَنَ" },
    { k: ["ishra", "ishrab"], ar: "اشرب", t: "اشْرَبْ" },
    { k: ["kitab", "kitaab", "ketab"], ar: "كتاب", t: "كِتَابٌ" },
    { k: ["alkitab"], ar: "الكتاب", t: "الْكِتَابُ" },
    { k: ["qalam", "kalam"], ar: "قلم", t: "قَلَمٌ" },
    { k: ["daftar"], ar: "دفتر", t: "دَفْتَرٌ" },
    { k: ["madrasa", "madrassa"], ar: "مدرسة", t: "مَدْرَسَةٌ" },
    { k: ["jami3a", "jamia", "jami3ah"], ar: "جامعة", t: "جَامِعَةٌ" },
    { k: ["talib", "taleb"], ar: "طالب", t: "طَالِبٌ" },
    { k: ["taliba", "talibah"], ar: "طالبة", t: "طَالِبَةٌ" },
    { k: ["mu3allim", "mouallim", "muallim"], ar: "معلم", t: "مُعَلِّمٌ" },
    { k: ["mu3allima", "mouallima"], ar: "معلمة", t: "مُعَلِّمَةٌ" },
    { k: ["lugha", "lougha", "lughah"], ar: "لغة", t: "لُغَةٌ" },
    { k: ["allarabiya", "alarabiya", "3arabiya", "arabiya", "arabiyya"], ar: "العربية", t: "الْعَرَبِيَّةُ" },
    { k: ["arabi", "3arabi", "arabiy"], ar: "عربي", t: "عَرَبِيٌّ" },
    { k: ["arabiyya", "3arabiyya"], ar: "عربية", t: "عَرَبِيَّةٌ" },
    { k: ["faransi", "français", "fransawi"], ar: "فرنسي", t: "فَرَنْسِيٌّ" },
    { k: ["inglizi", "english", "ingliziy"], ar: "إنجليزي", t: "إِنْجْلِيزِيٌّ" },
    { k: ["kalima", "kelima"], ar: "كلمة", t: "كَلِمَةٌ" },
    { k: ["jumla", "joumla"], ar: "جملة", t: "جُمْلَةٌ" },
    { k: ["harf"], ar: "حرف", t: "حَرْفٌ" },
    { k: ["haraka", "harakah"], ar: "حركة", t: "حَرَكَةٌ" },
    { k: ["tashkil", "tashkeel", "tachkil"], ar: "تشكيل", t: "تَشْكِيلٌ" },
    { k: ["damma"], ar: "ضمة", t: "ضَمَّةٌ" },
    { k: ["fatha", "fathah"], ar: "فتحة", t: "فَتْحَةٌ" },
    { k: ["kasra"], ar: "كسرة", t: "كَسْرَةٌ" },
    { k: ["sukun", "soukoun"], ar: "سكون", t: "سُكُونٌ" },
    { k: ["shadda", "chadda"], ar: "شدة", t: "شَدَّةٌ" },
    { k: ["tanwin", "tanween"], ar: "تنوين", t: "تَنْوِينٌ" },
    { k: ["clavier", "lohat", "lawha"], ar: "لوحة", t: "لَوْحَةُ" },
    { k: ["mafatih", "mafatiih"], ar: "مفاتيح", t: "مَفَاتِيحَ" },
    { k: ["bayt", "beit"], ar: "بيت", t: "بَيْتٌ" },
    { k: ["bab"], ar: "باب", t: "بَابٌ" },
    { k: ["shubbak", "choubbak"], ar: "شباك", t: "شُبَّاكٌ" },
    { k: ["madina", "madinah"], ar: "مدينة", t: "مَدِينَةٌ" },
    { k: ["balad"], ar: "بلد", t: "بَلَدٌ" },
    { k: ["yawm", "yaoum", "youm"], ar: "يوم", t: "يَوْمٌ" },
    { k: ["layl", "leil"], ar: "ليل", t: "لَيْلٌ" },
    { k: ["sabah"], ar: "صباح", t: "صَبَاحٌ" },
    { k: ["zuhr", "dhuhr", "dohr"], ar: "ظهر", t: "ظُهْرٌ" },
    { k: ["3asr", "asr"], ar: "عصر", t: "عَصْرٌ" },
    { k: ["maghrib"], ar: "مغرب", t: "مَغْرِبٌ" },
    { k: ["3isha", "isha"], ar: "عشاء", t: "عِشَاءٌ" },
    { k: ["usbu3", "ousbou3", "usbu"], ar: "أسبوع", t: "أُسْبُوعٌ" },
    { k: ["shahr", "chahr"], ar: "شهر", t: "شَهْرٌ" },
    { k: ["sana", "sanah"], ar: "سنة", t: "سَنَةٌ" },
    { k: ["sa3a", "saa3a", "saa"], ar: "ساعة", t: "سَاعَةٌ" },
    { k: ["dqiqa", "daqiqa"], ar: "دقيقة", t: "دَقِيقَةٌ" },
    { k: ["alyawm", "elyoum"], ar: "اليوم", t: "الْيَوْمَ" },
    { k: ["alana", "alan", "daba"], ar: "الآن", t: "الْآنَ" },
    { k: ["ghadan", "ghad"], ar: "غدا", t: "غَدًا" },
    { k: ["ams", "barah"], ar: "أمس", t: "أَمْسِ" },
    { k: ["wahid", "wahed", "wahidun"], ar: "واحد", t: "وَاحِدٌ" },
    { k: ["ithnan", "ithnayn", "zouj"], ar: "اثنان", t: "اثْنَانِ" },
    { k: ["thalatha", "tlata", "thalathah"], ar: "ثلاثة", t: "ثَلَاثَةٌ" },
    { k: ["arba3a", "arbaa", "arb3a"], ar: "أربعة", t: "أَرْبَعَةٌ" },
    { k: ["khamsa", "khamsah"], ar: "خمسة", t: "خَمْسَةٌ" },
    { k: ["sitta", "sitah"], ar: "ستة", t: "سِتَّةٌ" },
    { k: ["sab3a", "sabaa"], ar: "سبعة", t: "سَبْعَةٌ" },
    { k: ["thamaniya", "tmanya"], ar: "ثمانية", t: "ثَمَانِيَةٌ" },
    { k: ["tis3a", "tisa"], ar: "تسعة", t: "تِسْعَةٌ" },
    { k: ["ashara", "3ashara", "ashrah"], ar: "عشرة", t: "عَشَرَةٌ" },
    { k: ["ab", "abb"], ar: "أب", t: "أَبٌ" },
    { k: ["umm", "om", "oum"], ar: "أم", t: "أُمٌّ" },
    { k: ["ibn", "ben", "ibin"], ar: "ابن", t: "ابْنٌ" },
    { k: ["bint", "bent"], ar: "بنت", t: "بِنْتٌ" },
    { k: ["akh", "akhu", "khouya"], ar: "أخ", t: "أَخٌ" },
    { k: ["ukht", "okht", "khti"], ar: "أخت", t: "أُخْتٌ" },
    { k: ["zawj", "zawj"], ar: "زوج", t: "زَوْجٌ" },
    { k: ["zawja"], ar: "زوجة", t: "زَوْجَةٌ" },
    { k: ["sadiq", "sadiiq", "sahbi"], ar: "صديق", t: "صَدِيقٌ" },
    { k: ["sadiqa"], ar: "صديقة", t: "صَدِيقَةٌ" },
    { k: ["ism", "ismak", "ismek"], ar: "اسم", t: "اسْمٌ" },
    { k: ["maismuk", "maismek", "smiyetek"], ar: "ما اسمك", t: "مَا اسْمُكَ" },
    { k: ["ismi", "ismi"], ar: "اسمي", t: "اسْمِي" },
    { k: ["qahwa", "kahwa"], ar: "قهوة", t: "قَهْوَةٌ" },
    { k: ["shay", "chay", "atay"], ar: "شاي", t: "شَايٌ" },
    { k: ["ma", "maa", "water"], ar: "ماء", t: "مَاءٌ" },
    { k: ["khubz", "khobz", "khobez"], ar: "خبز", t: "خُبْزٌ" },
    { k: ["taam", "ta3am", "makla"], ar: "طعام", t: "طَعَامٌ" },
    { k: ["fawakih", "fawakeh"], ar: "فواكه", t: "فَوَاكِهُ" },
    { k: ["tuffah", "toffah", "tufaha"], ar: "تفاح", t: "تُفَّاحٌ" },
    { k: ["hubb", "houb", "7ob"], ar: "حب", t: "حُبٌّ" },
    { k: ["qalb", "kalb", "qalb"], ar: "قلب", t: "قَلْبٌ" },
    { k: ["hayat", "hayah"], ar: "حياة", t: "حَيَاةٌ" },
    { k: ["nur", "noor"], ar: "نور", t: "نُورٌ" },
    { k: ["salamun"], ar: "سلام", t: "سَلَامٌ" },
    { k: ["khayr", "kheir"], ar: "خير", t: "خَيْرٌ" },
    { k: ["sharr", "charr"], ar: "شر", t: "شَرٌّ" },
    { k: ["kabir", "kbir"], ar: "كبير", t: "كَبِيرٌ" },
    { k: ["saghir", "sghir", "saghir"], ar: "صغير", t: "صَغِيرٌ" },
    { k: ["jadid", "jdid"], ar: "جديد", t: "جَدِيدٌ" },
    { k: ["qadim", "qdim"], ar: "قديم", t: "قَدِيمٌ" },
    { k: ["hasan", "hassan"], ar: "حسن", t: "حَسَنٌ" },
    { k: ["jamiil", "jamil", "zwin"], ar: "جميل", t: "جَمِيلٌ" },
    { k: ["jamiila", "jamila"], ar: "جميلة", t: "جَمِيلَةٌ" },
    { k: ["sa3id", "saeed", "farhan"], ar: "سعيد", t: "سَعِيدٌ" },
    { k: ["hazin", "7azin"], ar: "حزين", t: "حَزِينٌ" },
    { k: ["sahl"], ar: "سهل", t: "سَهْلٌ" },
    { k: ["sa3b", "saab"], ar: "صعب", t: "صَعْبٌ" },
    { k: ["mumkin", "momkin"], ar: "ممكن", t: "مُمْكِنٌ" },
    { k: ["mustahil", "mustaheel"], ar: "مستحيل", t: "مُسْتَحِيلٌ" },
    { k: ["jayyid", "jayid"], ar: "جيد", t: "جَيِّدٌ" },
    { k: ["tamam", "tamaam"], ar: "تمام", t: "تَمَامٌ" },
    { k: ["ok", "okay", "hadi"], ar: "حسنا", t: "حَسَنًا" },
    { k: ["hasanan", "hasanan"], ar: "حسنا", t: "حَسَنًا" },
    { k: ["allah", "allah"], ar: "الله", t: "اللَّهُ" },
    { k: ["quran", "qorane", "qurane"], ar: "قرآن", t: "قُرْآنٌ" },
    { k: ["masjid", "mosque"], ar: "مسجد", t: "مَسْجِدٌ" },
    { k: ["salat", "salah"], ar: "صلاة", t: "صَلَاةٌ" },
    { k: ["duaa", "douaa", "dua"], ar: "دعاء", t: "دُعَاءٌ" },
    { k: ["arabikey"], ar: "أرابيكي", t: "أَرَابِيكِي" }
  ];

  var byLatin = Object.create(null);
  var byArabic = Object.create(null);

  function normKey(s) {
    return String(s || "")
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9']/g, "");
  }

  ENTRIES.forEach(function (entry) {
    entry.k.forEach(function (latn) {
      var key = normKey(latn);
      if (!key) return;
      if (!byLatin[key]) byLatin[key] = [];
      byLatin[key].push(entry);
    });
    var bare = entry.ar.replace(/[\u064B-\u065F\u0670]/g, "");
    byArabic[bare] = entry.t;
    byArabic[entry.ar] = entry.t;
  });

  var api = {
    entries: ENTRIES,
    byLatin: byLatin,
    byArabic: byArabic,
    normKey: normKey
  };

  root.ArabikeyLexicon = api;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }
})(typeof window !== "undefined" ? window : globalThis);
